AllCops:
  TargetRubyVersion: 2.2
  DisabledByDefault: true

# No trailing whitespace.
Style/TrailingWhitespace:
  Enabled: true

# Blank lines should not have any spaces.
Style/TrailingBlankLines:
  Enabled: true
